### ISSUE TITLE
Getting errors when sending data

### ISSUE THREAD

**Issue by HakanL** [datalust/seq-app-htmlemail#97]
I'm getting this error in the internal HtmlEmail diagnostics log:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HandlebarsDotNet.Collections.FixedSizeDictionary`3.AddOrReplace(TKey& key, TValue& value, EntryIndex`1& index)
   at HandlebarsDotNet.ValueProviders.ObjectIteratorValues..ctor(BindingContext bindingContext)
   at HandlebarsDotNet.Iterators.DictionaryIterator`3.Iterate(EncodedTextWriter& writer, BindingContext context, ChainSegment[] blockParamsVariables, Object input, TemplateDelegate template, TemplateDelegate ifEmpty)
   at HandlebarsDotNet.Iterators.DictionaryIterator`3.HandlebarsDotNet.Iterators.IIterator.Iterate(EncodedTextWriter& writer, BindingContext context, ChainSegment[] blockParamsVariables, Object input, TemplateDelegate template, TemplateDelegate ifEmpty)
   at HandlebarsDotNet.Compiler.Iterator.Iterate(BindingContext context, EncodedTextWriter writer, ChainSegment[] blockParamsVariables, Object target, TemplateDelegate template, TemplateDelegate ifEmpty)
   at lambda_method115(Closure , EncodedTextWriter& , BindingContext )
   at HandlebarsDotNet.Helpers.BlockHelpers.DelegateBlockHelperDescriptor.HandlebarsDotNet.Helpers.IHelperDescriptor<HandlebarsDotNet.BlockHelperOptions>.Invoke(EncodedTextWriter& output, BlockHelperOptions& options, Context& context, Arguments& arguments)
   at lambda_method116(Closure , EncodedTextWriter& , BindingContext )
   at HandlebarsDotNet.Helpers.BlockHelpers.DelegateBlockHelperDescriptor.HandlebarsDotNet.Helpers.IHelperDescriptor<HandlebarsDotNet.BlockHelperOptions>.Invoke(EncodedTextWriter& output, BlockHelperOptions& options, Context& context, Arguments& arguments)
   at lambda_method117(Closure , EncodedTextWriter& , BindingContext )
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass15_0.<Compile>b__0(TextWriter writer, Object context, Object data)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass16_0.<Compile>b__0(Object context, Object data)
   at Seq.App.EmailPlus.EmailApp.FormatTemplate(HandlebarsTemplate`2 template, Event`1 evt, Host host) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 216
   at Seq.App.EmailPlus.EmailApp.OnAsync(Event`1 evt) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 141
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 113
```

Settings:
```
{
  "From": "server@DOMAIN.com",
  "To": "hakan@DOMAIN.com",
  "SubjectTemplate": "",
  "Host": "smtp.gmail.com",
  "Port": 587,
  "EnableSsl": "True",
  "BodyTemplate": "",
  "SuppressionMinutes": 5,
  "Username": "server@DOMAIN.com",
  "Password": "[seq-preserve]"
}
```
Version: 3.1.0-dev-00179

I can send an event to the app and the email gets sent, but the automatic emails aren't sent.

**Comment by nblumhardt** [comment]
Thanks for the report, Hakan. It appears to be this problem:

https://github.com/Handlebars-Net/Handlebars.Net/pull/512

We'll check out what we can do to bundle an updated copy of the package :+1:

**Comment by liammclennan** [comment]
A [new version](https://www.nuget.org/packages/Seq.App.EmailPlus/3.1.1-dev-00197) has been published that includes the fix to Handlebars. Hopefully that fixes the problem for you.

**Comment by HakanL** [comment]
I have not seen the issue since the upgrade, I think we can call this resolved. Thanks for your quick help!
